betheluniversity/sciencelabs-python

- sciencelabs/__init__.py
- sciencelabs/lab_session/lab_session_controller.py
- sciencelabs/session/__init__.py
- sciencelabs/session/session_controller.py
- sciencelabs/templates/nav.html
- sciencelabs/templates/session/home.html
- sciencelabs/templates/users/add_user.html
- sciencelabs/templates/users/home.html
- sciencelabs/users/__init__.py
- sciencelabs/users/users_controller.py
The basic layout of the Users tab.
> Users Tab Template

- sciencelabs/db_repository/SessionRepo.py
- sciencelabs/db_repository/TutorSessionRepo.py
- sciencelabs/db_repository/UserRepo.py
- sciencelabs/session/__init__.py
- sciencelabs/templates/session/closed_sessions.html
The button that shows the tutors in the "closed sessions" tab works.
> Show Tutors Works!

- sciencelabs/db_repository/SessionRepo.py
- sciencelabs/db_repository/StudentSessionRepo.py
- sciencelabs/db_repository/TutorSessionRepo.py
- sciencelabs/db_repository/UserRepo.py
- sciencelabs/session/__init__.py
- sciencelabs/static/assets/css/sciencelabs.css
- sciencelabs/templates/session/add_anonymous.html
- sciencelabs/templates/session/add_student.html
- sciencelabs/templates/session/add_tutor.html
- sciencelabs/templates/session/closed_sessions.html
- sciencelabs/templates/session/delete_session.html
- sciencelabs/templates/session/edit_closed_session.html
- sciencelabs/templates/session/edit_student.html
- sciencelabs/templates/session/edit_tutor.html
A lot of work was done on the editing side of closed sessions. It's not complete, but the templates are created and a lot of the database info is populating.
> Edit closed sessions

- sciencelabs/db_repository/schedule_functions.py
- sciencelabs/db_repository/session_functions.py
- sciencelabs/session/__init__.py
- sciencelabs/static/assets/css/sciencelabs.css
- sciencelabs/templates/profile/home.html
- sciencelabs/templates/session/available_sessions.html
- sciencelabs/templates/session/base.html
- sciencelabs/templates/session/close_open_session.html
- sciencelabs/templates/session/closed_sessions.html
- sciencelabs/templates/session/create_session.html
- sciencelabs/templates/session/open_session.html
- sciencelabs/templates/session/restore_session.html
- sciencelabs/templates/session/student_attendance.html
- sciencelabs/templates/session/tutor_attendance.html
THIS IS NOT COMPLETE. It is laying the groundwork for future work on open sessions, but before I can do that we need some work on the "roles and permissions" side of things.
> Open sessions

- sciencelabs/db_repository/session_functions.py
- sciencelabs/sessions/__init__.py
- sciencelabs/templates/session/restore_session.html
Some things broke after merging roles-and-permissions. This fixes them.
> Some quick fixes after merge

- sciencelabs/course/__init__.py
- sciencelabs/email_tab/__init__.py
- sciencelabs/reports/__init__.py
- sciencelabs/schedule/__init__.py
- sciencelabs/sessions/__init__.py
- sciencelabs/term_startup/__init__.py
- sciencelabs/users/__init__.py
> added some route checking

- sciencelabs/db_repository/schedule_functions.py
- sciencelabs/sessions/__init__.py
- sciencelabs/templates/email_tab/base.html
- sciencelabs/templates/nav.html
- sciencelabs/templates/profile/home.html
- sciencelabs/templates/reports/base.html
- sciencelabs/templates/session/available_sessions.html
- sciencelabs/templates/session/base.html
- sciencelabs/templates/session/close_open_session.html
Deleted some leftover TODOs that have been handled previously, and added in a couple of fixes for existing TODOs.
> TODO fixes

- sciencelabs/static/assets/js/sciencelabs.js
- sciencelabs/templates/reports/session.html
- sciencelabs/templates/schedule/schedules.html
- sciencelabs/templates/sciencelabs_base.html
- sciencelabs/templates/session/add_student.html
- sciencelabs/templates/session/available_sessions.html
- sciencelabs/templates/session/closed_sessions.html
- sciencelabs/templates/session/edit_closed_session.html
- sciencelabs/templates/session/edit_student.html
- sciencelabs/templates/session/restore_session.html
- sciencelabs/templates/users/edit_user.html
- sciencelabs/templates/users/select_user_roles.html
Deleted a bunch of commented out code and moved some shared JS to a file that gets pulled in.
> JS refactor

- sciencelabs/sessions/__init__.py
- sciencelabs/templates/session/add_anonymous.html
- sciencelabs/templates/session/delete_session.html
Refactoring name so we don't confuse the flask session with the lab session
> session -> session_info

- sciencelabs/__init__.py
- sciencelabs/course/__init__.py
- sciencelabs/db_repository/__init__.py
- sciencelabs/db_repository/course_functions.py
- sciencelabs/db_repository/db_tables.py
- sciencelabs/db_repository/schedule_functions.py
- sciencelabs/db_repository/session_functions.py
- sciencelabs/db_repository/user_functions.py
- sciencelabs/profile/__init__.py
- sciencelabs/reports/__init__.py
- sciencelabs/schedule/__init__.py
- sciencelabs/sessions/__init__.py
- sciencelabs/templates/macros/macros.html
- sciencelabs/templates/nav.html
- sciencelabs/templates/profile/role_viewer.html
- sciencelabs/templates/reports/course.html
- sciencelabs/templates/reports/session.html
- sciencelabs/templates/reports/student.html
- sciencelabs/templates/reports/term.html
- sciencelabs/templates/reports/view_session.html
- sciencelabs/templates/schedule/create_new_schedule.html
- sciencelabs/templates/schedule/edit_schedule.html
- sciencelabs/templates/schedule/schedules.html
- sciencelabs/templates/session/edit_session.html
- sciencelabs/templates/term_startup/step_one.html
- sciencelabs/templates/users/edit_user.html
- sciencelabs/templates/users/users.html
- sciencelabs/users/__init__.py
- sciencelabs/views.py
Refactored database code with better variable names and also session.close() so that data gets updated between threads on the webpage. Also did a few bug fixes as they came up when I was clicking around.
> Database fix

- sciencelabs/__init__.py
- sciencelabs/db_repository/session_functions.py
- sciencelabs/sciencelabs_controller.py
- sciencelabs/sessions/__init__.py
- sciencelabs/templates/sessions/student_attendance.html
- sciencelabs/templates/sessions/student_sign_in.html
- sciencelabs/views.py
i'm trying to take just the "good" changes
> Auth testing

- sciencelabs/db_repository/course_functions.py
- sciencelabs/db_repository/user_functions.py
- sciencelabs/email_tab/email_controller.py
- sciencelabs/reports/__init__.py
- sciencelabs/templates/reports/course.html
- sciencelabs/templates/reports/view_student.html
- sciencelabs/templates/users/edit_user.html
- sciencelabs/users/__init__.py
We kind of forgot about Course Viewers for a while... but this PR fixes that! Everywhere that course viewers should see info has been updated, and some links have been disabled for professors view so they aren't tempted to click somewhere that will lead them astray.
> Course viewers

- sciencelabs/__init__.py
- sciencelabs/db_repository/user_functions.py
- sciencelabs/sessions/__init__.py
- sciencelabs/term_startup/__init__.py
This PR accomplishes these things:
- When users visit the lab or go to the site when they have been soft deleted their accounts are reactivated.
- At the end of the semester all users who have the student role as their only role get soft deleted.
- At the end of the semester all lead tutors get demoted to regular tutor roles.
The last two points happen during the transition between semesters.
> User activation

- sciencelabs/db_repository/schedule_functions.py
- sciencelabs/db_repository/user_functions.py
- sciencelabs/sessions/__init__.py
- sciencelabs/term_startup/__init__.py
This PR:
- Adds student role for anybody who signs into an open session as a student
- Pulls in student courses when they are activated
- Pulls in courses and profs from banner on new term startup (don't have to wait for cron to run)
- A couple of small refactors.
> New term fix

- sciencelabs/templates/profile/role_viewer.html
- sciencelabs/templates/users/users.html
Displays messages to avoid act-as going too many levels deep. Fixes Issue #93
> Act as role fix

- sciencelabs/__init__.py
- sciencelabs/sessions/__init__.py
- sciencelabs/templates/sessions/student_attendance.html
- sciencelabs/templates/sessions/tutor_attendance.html
Made the logic a little nicer for which route we take for open sessions depending on the environment (dev vs prod).
> better route handling

- sciencelabs/sessions/__init__.py
- sciencelabs/templates/sessions/create_session.html
- sciencelabs/templates/sessions/edit_session.html
I honestly thought this was going to be a much bigger fix than it ended up being. All this PR accomplishes is a couple more checks for creating/editing sessions so we don't get any strange behavior or lose sessions in the system. Fixes #104.
> Edit session fixes

- sciencelabs/__init__.py
- sciencelabs/error.py
- sciencelabs/sessions/__init__.py
- sciencelabs/static/assets/css/sciencelabs.css
- sciencelabs/templates/error/403.html
- sciencelabs/templates/error/404.html
- sciencelabs/templates/error/500.html
- sciencelabs/templates/error/503.html
- sciencelabs/templates/error/error.html
Created error pages to handle any failures nicely and give the user feedback. Also hooked up the flask errorhandlers to display those pages. Fixes #106 and Fixes #107
> Error pages

- sciencelabs/__init__.py
- sciencelabs/db_repository/session_functions.py
I thought this was going to be WAY more involved, but since we had a datetimeformat method already that we used in the templates it ended up being super easy. The times now format like we want them too. As I was clicking around checking on stuff I found a bug, which is what the 2nd commit is, otherwise this would have only been the first commit. Fixes #110
> Bethel time formats

- sciencelabs/course/__init__.py
- sciencelabs/email_tab/__init__.py
- sciencelabs/reports/__init__.py
Fixed some links that break if you try to go there directly by url. I also went through and checked to make sure that all reports are deep linkable (as long as you know the id of whatever report you want to view). I think we should be good here unless @c-schwarze can think of anything else 😄 Fixes #111
> Deep linkable fixes

- sciencelabs/sessions/__init__.py
- sciencelabs/templates/sessions/tutor_attendance.html
The Lead tutor has the abillity to edit the session and attendance, but the route checking doesn't allow it currently. Fixed now.
> Lead Tutor Editing

- sciencelabs/__init__.py
- sciencelabs/course/__init__.py
- sciencelabs/email_tab/__init__.py
- sciencelabs/profile/__init__.py
- sciencelabs/schedule/__init__.py
- sciencelabs/sciencelabs_controller.py
- sciencelabs/sessions/__init__.py
- sciencelabs/templates/macros/semester_selector.html
- sciencelabs/templates/sessions/add_student.html
- sciencelabs/templates/sessions/add_tutor.html
- sciencelabs/term_startup/__init__.py
- sciencelabs/users/__init__.py
Reverts betheluniversity/sciencelabs-python#130
This fixed the problem but created a more serious new one. I have a fix ready as explained in issue #129
> Revert "Delayed alert fixes"

- sciencelabs/db_repository/user_functions.py
- sciencelabs/sessions/__init__.py
I went through and checked out everywhere we can WSAPI. There are a couple of places we needed better checking in case something goes wrong. In most cases we were good to go though. Fixes #136
> Wsapi error handling

- sciencelabs/course/__init__.py
- sciencelabs/schedule/__init__.py
- sciencelabs/sessions/__init__.py
- sciencelabs/term_startup/__init__.py
- sciencelabs/users/__init__.py
Expanded some alert messages to give more/better info.
> Alert Messages

- sciencelabs/db_repository/user_functions.py
- sciencelabs/email_tab/email_controller.py
When emails get sent to the student group we do a quick check now to see if the student has attended any sessions. If not, we don't bother sending them the email. Also in places where it was popping up I removed the API User role. Finally, I also added in some better checking for recipients and bcc during testing.
> Email student check

- sciencelabs/__init__.py
- sciencelabs/reports/__init__.py
CSV Downloads weren't working, this fixes that in a pretty elegant way. No storing of data, just create the file and hand it off to the user. It's called "better fix" because I had another branch where I tried some other things that weren't as successful or good.
> Csv download better fix

- sciencelabs/static/assets/css/sciencelabs.css
- sciencelabs/templates/users/user_search_results.html
- sciencelabs/users/__init__.py
- sciencelabs/wsapi/wsapi_controller.py
Handle if there are spaces leading or trailing the name. Display error if this happens.
> Search user fix

- sciencelabs/course/__init__.py
- sciencelabs/db_repository/course_functions.py
Delete course was trying to do too much and was causing errors. Simplified and fixed.
> Refactor delete method

- sciencelabs/static/assets/css/sciencelabs.css
- sciencelabs/templates/email_tab/base.html
- sciencelabs/templates/email_tab/send_email_confirm.html
- sciencelabs/templates/profile/role_viewer.html
- sciencelabs/templates/schedule/create_new_schedule.html
- sciencelabs/templates/schedule/edit_schedule.html
- sciencelabs/templates/sciencelabs_base.html
- sciencelabs/templates/sessions/create_session.html
- sciencelabs/templates/sessions/edit_session.html
- sciencelabs/templates/users/users.html
> slimselect refactor

- sciencelabs/db_repository/session_functions.py
- sciencelabs/sessions/__init__.py
- sciencelabs/templates/sessions/edit_session.html
- sciencelabs/templates/sessions/edit_student.html
- sciencelabs/templates/sessions/edit_tutor.html
Need to edit/delete based on studentSession or tutorSession because students and tutors can come to sessions twice. This went deep, so lots of changes.
> Delete user from session

- requirements.txt
- sciencelabs/__init__.py
- sciencelabs/error.py
- sciencelabs/reports/__init__.py
Removed raven/sentry legacy stuff and updated to the latest version.
> Sentry Updates

- sciencelabs/db_repository/user_functions.py
- sciencelabs/sessions/__init__.py
We handle both CAS and card-swipe checkins, but some of our checks were only applied for the card-swipe.
> Move checks out

- sciencelabs/course/__init__.py
- sciencelabs/db_repository/course_functions.py
- sciencelabs/db_repository/schedule_functions.py
- sciencelabs/term_startup/__init__.py
Do some basic checking on semester start up. Also a quick course fix.
> Semester checks

- sciencelabs/static/assets/css/sciencelabs.css
- sciencelabs/templates/nav.html
- sciencelabs/templates/sciencelabs_base.html
Added a testing banner to distinguish xp and prod since I have both up at the same time a lot and I want to be able to tell quickly which one I'm looking at.
> Added a Testing Banner

- sciencelabs/db_repository/schedule_functions.py
- sciencelabs/reports/__init__.py
fixed the term numbers and the rest of the report numbers not lining up.
> Fixed numbers not lining up

- sciencelabs/course/__init__.py
- sciencelabs/db_repository/course_functions.py
- sciencelabs/reports/__init__.py
- sciencelabs/templates/reports/view_course.html
Need to deal better with situation where 2+ profs are team teaching a course.
> Handle multiple profs

- sciencelabs/templates/reports/course.html
Lost the column header at some point.
- Small Change
- Bug fix
Locally
> Added column

- sciencelabs/db_repository/user_functions.py
Check if course exists before setting so we don't attempt to create a duplicate.
- Small Change
- Bug fix
locally
> check if course exists

- sciencelabs/db_repository/course_functions.py
Changed a query to get the right courses when editing a student
- Bug fix
Please briefly describe the tests that you ran to verify your changes.
I ran it locally and it pulled in the correct courses for a few test students
> updated query to grab the right courses when editing a student

- sciencelabs/templates/reports/course.html
Changed title of column to accurately describe what the column displays.
- Bug fix
N/A
> fix title of table column on report/course

- sciencelabs/__init__.py
Fixed sentry import statement which caused errors if you tried to import error while not on prod
- Bug fix
It works
> fix sentry import

- sciencelabs/templates/reports/enrollment.html
> Change data

- sciencelabs/course/__init__.py
- sciencelabs/wsapi/wsapi_controller.py
If the courses get pulled before the semester starts, send with a date offset to get future courses.
- Bug fix
locally
> date offset

- sciencelabs/db_repository/session_functions.py
- sciencelabs/reports/__init__.py
- sciencelabs/templates/reports/base.html
- sciencelabs/templates/reports/view_course.html
- sciencelabs/templates/reports/view_course_session.html
- sciencelabs/templates/term_startup/step_one.html
Added in a new page to display attendance for a specific course and session which is accessed by clicking on the session attendees number on the view course page
- New feature
I updated and viewed the changes locally and everything seems to check out
> Instructor attendance per session

- sciencelabs/reports/__init__.py
Just a hotfix updating some method calls that I forgot to update
> session hotfix

- sciencelabs/course/__init__.py
- sciencelabs/email_tab/email_controller.py
- sciencelabs/reports/__init__.py
- sciencelabs/schedule/__init__.py
- sciencelabs/sessions/__init__.py
- sciencelabs/users/__init__.py
Build out lists and dictionaries better. I've been meaning to do this refactor forever and I finally got around to it.
Fixes #144 
Locally
> Better dicts/lists

- sciencelabs/error.py
> Don't log 403s

- sciencelabs/db_repository/session_functions.py
- sciencelabs/schedule/__init__.py
- sciencelabs/static/assets/css/sciencelabs.css
- sciencelabs/templates/schedule/schedules.html
Adds the ability to duplicate schedules in order to save time.
- New feature
Tested this locally.
> Schedule duplication

- sciencelabs/db_repository/session_functions.py
- sciencelabs/student/__init__.py
- sciencelabs/templates/student/reservations.html
Use room capacity as a fallback in room groups
- New feature
Tested locally
> Dynamic room capacity

- sciencelabs/db_repository/user_functions.py
- sciencelabs/templates/users/base.html
- sciencelabs/templates/users/reactivate_user.html
- sciencelabs/users/__init__.py
Adds a new tab to the Users section that allows administrators to activated deactivated users
Fixes #150 
- New feature
Please briefly describe the tests that you ran to verify your changes.
I looked at the new page locally and tested deactivating and reactivating users.
> Adds a tab to reactivate users

- sciencelabs/db_repository/db_tables.py
- sciencelabs/db_repository/schedule_functions.py
- sciencelabs/db_repository/session_functions.py
- sciencelabs/schedule/__init__.py
- sciencelabs/sessions/__init__.py
- sciencelabs/student/__init__.py
- sciencelabs/templates/index.html
- sciencelabs/templates/reports/view_session.html
- sciencelabs/templates/schedule/create_new_schedule.html
- sciencelabs/templates/schedule/edit_schedule.html
- sciencelabs/templates/schedule/view_room_groupings.html
- sciencelabs/templates/schedule/zoom_setup.html
- sciencelabs/templates/sessions/add_student.html
- sciencelabs/templates/sessions/available_sessions.html
- sciencelabs/templates/sessions/create_session.html
- sciencelabs/templates/sessions/edit_session.html
- sciencelabs/templates/sessions/edit_student.html
- sciencelabs/templates/sessions/student_attendance.html
- sciencelabs/templates/sessions/view_session.html
Adds ability to use the reservation system or not when creating or editing sessions/schedules. Zoom links are now optional. Capacity is only used when using the reservation system. Adjusts behavior across app to account for these changes. Adds documentation.
Fixes #219 
- Medium Change - 2+ people need to review this
- New feature
- New database columns:
- ALTER TABLE session ADD COLUMN usingReserveSys TinyInt(1) DEFAULT NULL;
- ALTER TABLE schedule ADD COLUMN usingReserveSys TinyInt(1) DEFAULT NULL;
I created/edited sessions/schedules locally and looked closely at their behaviors when created and when opened. 
> Reservation System Changes
